name: shoppist
description: A simple shoping list & accounting app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  shared_preferences: ^2.0.15
  freezed: ^2.2.0
  get_it: ^7.2.0
  injectable: ^1.5.3
  go_router: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.3.2
  injectable_generator: ^1.5.4
  freezed_annotation: ^2.2.0

flutter:
  uses-material-design: true
