name: shoppist
description: A simple shoping list & accounting app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dio: ^5.2.1+1
  shared_preferences: ^2.2.0
  freezed: ^2.3.5
  get_it: ^7.6.0
  go_router: ^9.0.2
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
