name: shoppist
description: A simple shoping list & accounting app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  dio: ^5.4.2+1
  shared_preferences: ^2.2.2
#  freezed: ^2.4.1
  get_it: ^7.6.8
  go_router: ^13.2.3
#  freezed_annotation: ^2.4.1
  firebase_core: ^2.29.0
  slang: ^3.30.2
  slang_flutter: ^3.30.0
  equatable: ^2.0.5
  cloud_firestore: ^4.16.1
  swipe_refresh: ^1.1.0
  uuid: ^4.4.0
  share_plus: ^8.0.3
  dropdown_button2: ^2.3.9
  awesome_notifications_core: ^0.9.3
  awesome_notifications: any
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
